package org.naturenet.data.model;

import android.os.Parcel;
import android.os.Parcelable;

public class Comment implements Parcelable {
    public Comment() {}

    /**
     * unique autogenerated-id for the comment
     */
    public String id;
    /**
     * the id of the user who created the comment
     */
    public String commenter;
    /**
     * the user submitted comment text
     */
    public String comment;

    protected Comment(Parcel in) {
        id = in.readString();
        commenter = in.readString();
        comment = in.readString();
    }

    public static final Creator<Comment> CREATOR = new Creator<Comment>() {
        @Override
        public Comment createFromParcel(Parcel in) {
            return new Comment(in);
        }

        @Override
        public Comment[] newArray(int size) {
            return new Comment[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(commenter);
        dest.writeString(comment);
    }

    @Override
    public String toString() {
        return "Comment{" +
                "id='" + id + '\'' +
                ", commenter='" + commenter + '\'' +
                ", comment='" + comment + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Comment comment1 = (Comment) o;

        if (!id.equals(comment1.id)) return false;
        if (!commenter.equals(comment1.commenter)) return false;
        return comment.equals(comment1.comment);

    }

    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + commenter.hashCode();
        result = 31 * result + comment.hashCode();
        return result;
    }
}
