package org.naturenet.data.model;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.List;

public class Observation implements Parcelable {
    public Observation() {}

    /**
     * unique autogenerated-id for the observation
     */
    public String id;
    /**
     * the id of the activity location pair this observation was recorded for
     */
    public String activity_location;
    /**
     * the id of the user who submitted the observation
     */
    public String observer;
    /**
     * the location where the observation took place
     */
    public String location;
    /**
     * freeform data submitted as part of the observation
     */
    public Parcelable data;
    /**
     * comments by other users on the observation, may be null/not present if there are no comments
     */
    public List<Comment> comments = null;

    protected Observation(Parcel in) {
        id = in.readString();
        activity_location = in.readString();
        observer = in.readString();
        location = in.readString();
        //TODO data = in.readParcelable()
        comments = in.createTypedArrayList(Comment.CREATOR);
    }

    public static final Creator<Observation> CREATOR = new Creator<Observation>() {
        @Override
        public Observation createFromParcel(Parcel in) {
            return new Observation(in);
        }

        @Override
        public Observation[] newArray(int size) {
            return new Observation[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(id);
        dest.writeString(activity_location);
        dest.writeString(observer);
        dest.writeString(location);
        dest.writeParcelable(data, flags);
        dest.writeTypedList(comments);
    }
}
